### ISSUE TITLE
GitHub not listing all releases

### ISSUE THREAD

**Issue by JohnCoates** [HanaDigital/grev#5]
Not all releases are counted. For example try https://github.com/JohnCoates/Aerial

**Comment by dr-nyt** [comment]
Hey, sorry for the delayed response, was really busy.

This web app gets all your repository data directly from the Github API. I have double-checked, and the Github API only returns release statistics up to version 1.9.1 for your repository. I have got in touch with Github Support and hopefully, they will find a fix for this, otherwise, there doesn't seem to be any other method to track your old releases.

I will get back to you as soon as I have an answer, cheers!

**Comment by JohnCoates** [comment]
Thanks for debugging this! I appreciate your response

**Comment by latenitefilms** [comment]
Same issue with: https://hanadigital.github.io/grev/?user=commandpost&repo=commandpost

**Comment by dr-nyt** [comment]
I finally found a fix, expect an update soon 👌

**Comment by dr-nyt** [comment]
Fixed! The download counts jumped by a lot.

**Comment by JohnCoates** [comment]
Great job! I appreciate you taking the time to do this

**Comment by latenitefilms** [comment]
Legend, thanks!
